### ISSUE TITLE
[Android] 볼륨 업/다운 감지하는 로직에 의해 앱이 키보드를 못띄우는 현상

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter_hardware_buttons#13]
지금 안드로이드에서 딱히 방법이 없어서 꼼수로 보이지 않는 윈도우 뷰를 새로 만들어서 거기서 KeyEvent를 처리하도록 했는데요, 그러다보니 앱에서 키보드가 안나오는 버그가 있습니다 ㅋㅋㅋ
[이 사람](https://stackoverflow.com/a/39205226)도 문제 자체는 다르지만 비슷하게 윈도우 뷰를 쓰는 방식을 한게 있는데, 아래 댓글로 "Brilliant! Thanks. One problem here is that soft keyboard cant be opened :(" 라고 하네요 ㅎ.ㅎ....

윈도우 뷰를 띄우지말고 다른 방식을 찾아봐야하나 해서 삽질을 꽤 많이 해봤는데 지금까지 알기로는 그냥 윈도우 뷰를 계속 쓰는게 나은거같고.
일단 삽질 결과 해결 방법은 찾은거같아서 풀리퀘 올릴게요.

하.. 근데 애초에 보이지않는 윈도우 뷰를 만든다는거 자체가 뭔가 불안하네요 ㅋㅋㅋㅋㅋ

**Comment by songyiYu** [comment]
interesting!
