### ISSUE TITLE
10월 6일 오프라인 회의

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter_hardware_buttons#16]
1. 안드로이드
- 권한 요청 루트 점검
- 테스트

2. ios
- 버전 테스트
- mute일때 볼륨 down 눌러도 DOWN 뜨도록

3. 공통
- https://flutter.dev/docs/development/packages-and-plugins/developing-packages
- 이거 보면서 필요 문서 작성 및 배포

**Comment by songyiYu** [comment]
꼼꼼솔

**Comment by giantsol** [comment]
1. README.md
- 다른 플러그인에 README 형식 참조해서 작성

2. CHANGELOG.md ??
- 이건 뭥미

3. LICENSE 파일 작성
- 이것도 다른 플러그인 참조해서 작성
- Code Usage
- Screenshots
- Link to the corresponding code repository

4. API documentation
- `dartdoc`이란 커맨드 사용하면 되는듯
- [참조](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#api-documentation)

5. 배포
- `flutter publish --dry-run`으로 확인
- `flutter publish`로 배포

**Comment by giantsol** [comment]
- example/README.md
- README.md 업데이트

**Comment by giantsol** [comment]
완-료
