### ISSUE TITLE
[ios] lock button detection timing issue

### ISSUE THREAD

**Issue by yenoss** [flutter-moum/flutter_hardware_buttons#27]
## Description of the issue
Lock button plugin can't detect immediately. 
It's detecting when the app returns from background to foreground.

Users who use the plugin will expect Immediate detection. (like a  home button action)

Do you plan to provide this feature in the future?  

If you don't support it, I think you should write the README about this timing issue.

Thanks.

**Comment by songyiYu** [comment]
There is no issue on iphone6 (ios12)

**Comment by giantsol** [comment]
Thanks.
Closing it cause there seems to be no issue :3
