### ISSUE TITLE
How to use HardwareButtons Enum ?

### ISSUE THREAD

**Issue by songyiYu** [flutter-moum/flutter_hardware_buttons#28]
<img width="609" alt="스크린샷 2019-10-19 오후 2 05 18" src="https://user-images.githubusercontent.com/9947963/67138093-b4375300-f279-11e9-9e0e-331dfc3758a3.png">

I can't find HardwareButtons in code.
Do I have to implement HardwareButtons enum by myself?

**Comment by giantsol** [comment]
Change

```dart
import 'package:hardware_buttons/hardware_buttons.dart';
```

as:

```dart
import 'package:hardware_buttons/hardware_buttons.dart' as HardwareButtons;
```

then it'll find the variables properly.

I'll update example README to include import statements.
Thanks :)
