### ISSUE TITLE
안드로이드 memory leak 이슈

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter_hardware_buttons#3]
음.. 하다보니까 안드로이드에서 작업할 때 EventChannel.StreamHandler 인터페이스를 override 해서 onListen 함수에서 버튼 감지 이벤트 듣기 시작하고 onCancel 함수에서 듣던거 캔슬하는데, 앱이 종료되어도 onCancel 함수가 안불리는 버그가 있나봐여.
그래서 앱을 꺼도 버튼 감지 이벤트 캔슬이 안되어서 플러터 앱은 종료되었는데 자꾸 메시지 보내려고하니까 "W/FlutterJNI: Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter.moum.hardware_buttons.volume. Response ID: 0" 요론 메시지가 계속 올라가네요.

이런 버그가 있어서 [battery](https://github.com/flutter/plugins/tree/master/packages/battery) 라는 플러그인에서도 이거 회피하려고하는 [풀리퀘](https://github.com/flutter/plugins/pull/1992)를 진행중인듯.

위 풀리퀘보고 좀 따라해서 회피해야할듯. 결국은 플러터팀에서 onCancel 함수가 제대로 불리도록 수정해 줘야겠지만!

iOS는 이런 버그가 없을수도 있지만 혹여나 앱을 종료했을 때 위와 같은 에러 메시지 안뜨나 확인해보심 좋을듯여~

나중을 위해 적어둠!

**Comment by songyiYu** [comment]
Wow.. 이런 버그가 있었군요.. 어쩐지....

**Comment by giantsol** [comment]
오?? 커밋에 이슈 링크 달면 위에있는 메시지들이 생기네 싱기 ㅋㅋㅋ
어쨌든 이 이슈는 인지하고 있으므로 클로즈
