### ISSUE TITLE
Not detect event volume

### ISSUE THREAD

**Issue by nexussmart** [flutter-moum/flutter_hardware_buttons#36]
Hi,

On iPhone 6s plus, there is no event volume up and volume down.

`hardware_buttons: ^0.2.2`

`void initState() {
    super.initState();
    _volumeButtonSubscription = volumeButtonEvents.listen((VolumeButtonEvent event) {
      print(event);
      setState(() {
        hasClickVolumeDown = VolumeButtonEvent.VOLUME_DOWN == event;
        hasClickVolumeDown = VolumeButtonEvent.VOLUME_UP == event;
      });
    });
  }`

**Comment by giantsol** [comment]
Hi @nexussmart !
Will have a look at that tomorrow :)
Thanks!

**Comment by nexussmart** [comment]
For information,
If I click on the Power button and return to the app, the volume events are detected.

**Comment by supratikkoley** [comment]
Any update on this issue?

**Comment by giantsol** [comment]
Hi!
Sorry we were busy lately.
We're going to have a look at this shortly!
Thanks.

**Comment by giantsol** [comment]
Hello @nexussmart 
We tested it on iPhone 6s plus os 12.0 and it seems to be fine.
Could you tell me the version number?
Thanks

**Comment by nexussmart** [comment]
Hi,

iPhone 6S Plus ios 10.3.3

Moreover,`_volumeButtonSubscription?.cancel()` closes the application brutally.

**Comment by giantsol** [comment]
I've reproduced the problem with iPhone 6S Plus ios 10.3.3.
Will fix it ASAP.
Thanks.

**Comment by eojine** [comment]
Hi, @nexussmart and @supratikkoley 
I think we've modified the volume button bug.
If you think there are other issues, please leave a comment.
Thanks.

**Comment by nexussmart** [comment]
Thanks,

Nice work
