### ISSUE TITLE
Kotlin Migration

### ISSUE THREAD

**Issue by nexussmart** [flutter-moum/flutter_hardware_buttons#39]
Hi,

Do you have the opportunity to upgrade the version of kotlin ?

> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
> The following dependencies do not satisfy the required version:
> project ':hardware_buttons' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by giantsol** [comment]
Hi @nexussmart !
I'll have a look.
Thanks

**Comment by giantsol** [comment]
Hi @nexussmart ,
We've upgraded kotlin version in version ```0.2.4```.

Just in case you need to know, we've also migrated to AndroidX in version ```1.0.0```, so if you need to use AndroidX, use ```1.0.0```, or if you just wanna go with the original support libraries, you can keep using ```0.2.4```.

Thanks~!

**Comment by nexussmart** [comment]
Thanks
