### ISSUE TITLE
홈버튼 감지 구현

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter_hardware_buttons#7]

**Comment by giantsol** [comment]
일단 안드/ios 둘 다 되는걸로!

**Comment by eojine** [comment]
홈버튼 감지 리젝사유는 아직 발견 못했으니 일단 만들어놓는걸로~~

**Comment by giantsol** [comment]
찾아봤는데 안드가 잘 될지는 해봐야알듯해요
[요런 방식](https://stackoverflow.com/a/27956263)이 있다고 말하긴하는데 음.. 테스트해봐야할듯

**Comment by songyiYu** [comment]
> 찾아봤는데 안드가 잘 될지는 해봐야알듯해요
> [요런 방식](https://stackoverflow.com/a/27956263)이 있다고 말하긴하는데 음.. 테스트해봐야할듯

**Comment by giantsol** [comment]
아니 근데 요게 [KEYCODE_HOME](https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_HOME)이 시스템상에서만 처리하고 앱쪽으로는 안내려준다고 적혀있는데, 제가 구현한 방식이 window에 view를 다는 방식이라서 잘하면 내려올수도.... 내려오면 쉬울텐데

**Comment by songyiYu** [comment]
> 아니 근데 요게 [KEYCODE_HOME](https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_HOME)이 시스템상에서만 처리하고 앱쪽으로는 안내려준다고 적혀있는데, 제가 구현한 방식이 window에 view를 다는 방식이라서 잘하면 내려올수도.... 내려오면 쉬울텐데

헐 window 에 view 를 다는 방식으로 시스템에서만 처리하는 값을 가져올 수 있을까요??
되면 대박인데...

**Comment by giantsol** [comment]
아 안내려오네요 ㅋㅋㅋㅋㅋ

**Comment by giantsol** [comment]
ㅋㅋㅋ 포스 푸시 해버리니까 댓글이 2개씩 달려버리넴
