### ISSUE TITLE
락버튼(안드로이드) / 사일런트 버튼(iOS) 구현

### ISSUE THREAD

**Issue by giantsol** [flutter-moum/flutter_hardware_buttons#8]
안드로이드는 일단 락버튼을 감지할 수 있는걸로 아는데, 갓진님이 알아본 바로 iOS에서는 막혀있다고 한다.
안드로이드도 조사는 해 봐야 한다. 락버튼을 오래 누르면 락이 되는게아니고 전원 끄기/다시 시작 이런 메뉴가 뜨는데 이런걸 분기태울수 있는지.. 분기를 태우긴 해야하는지를 고민해봐야 한다.

iOS는 어짜피 락버튼을 할 수 없기 때문에 그 시간에 silent 버튼 감지를 구현할 수 있는지 알아보고, 가능하다면 이걸 진행!

**Comment by eojine** [comment]
애플은 싫어하는거 투성이다...

**Comment by eojine** [comment]
갓솔~~~~~~!

**Comment by songyiYu** [comment]
ios 락버튼 홈버튼 
https://github.com/ImEric/swift-home-vs-lock-button 참조해보세요 :)

**Comment by giantsol** [comment]
요건 아마도 간단해보이네여
https://stackoverflow.com/questions/6848518/detect-on-off-key-press-android

**Comment by giantsol** [comment]
아니.. KEYCODE_POWE가 안먹히는거같은데..

**Comment by giantsol** [comment]
흠.. 락버튼 안드 꽤 많이 어려워보이네요 ㅠ

**Comment by songyiYu** [comment]
> 흠.. 락버튼 안드 꽤 많이 어려워보이네요 ㅠ

락버튼 감지가 좀 어려우면 락스크린을 감지하는것은 어떤가요?

**Comment by giantsol** [comment]
후.. 천신만고의 세월 끝에 락버튼 구현을 알아냈다.
스택오버플로우 찾아보면 어딜가나 Intent.ACTION_CLOSE_SYSTEM_DIALOGS로 어쩌구 한다 해서 그걸로 아무리 해보려해도 안됐는데
콘솔에서 `adb shell dumpsys activity` 떠서 보니까 Intent.ACTION_SCREEN_OFF로도 reason값이 내려왔었다.
고거 보니까 `PowerManager.GO_TO_SLEEP_REASON_TIMEOUT` 또는 `PowerManager.GO_TO_SLEEP_REASON_POWER_BUTTON` 이런걸로 구분할 수 있어서 요걸로 했당.

**Comment by giantsol** [comment]
안드랑 iOS 둘다 락버튼 감지하는걸로 했으니까 사일런트버튼은 일단 하지 않는걸로합시당 @eojine
